services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=pizzeria'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=123456789'
      - 'MYSQL_USER=pizza'
    ports:
      - '3306:3306'
